---

- block:
    - name: Obtain SSO token with using username/password credentials
      ovirt_auth:
        url: "{{ rhv_url }}"
        username: "{{ rhv_user }}"
        password:  "{{ rhv_pass }}"
        insecure: true

    - ovirt_vms:
        auth: "{{ ovirt_auth }}"
        state: absent
        name: "{{ item }}"
      loop: "{{ vm_names }}"
      ignore_errors: True

    - ovirt_vms:
        auth: "{{ ovirt_auth }}"
        state: running
        template: RHV_RHEL75_CLEAN_TPL
        name: "{{ item }}"
        cluster: lenovo-sr650-01
        wait: true
      loop: "{{ vm_names }}"

  always:
    - name: Always revoke the SSO token
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
