---

- name : upload answerbot
  copy:
    src: "{{ role_path }}/bin/answerbot"
    dest: /tmp/answerbot
    mode: 0755

- name: run answerbot in login mode
  command: /tmp/answerbot -l
  ignore_errors: True


- name: run answerbot in engine-cleanup mode
  command: /tmp/answerbot -e
  ignore_errors: True

- name: remove the old version rhvm
  yum:
    name: "rhvm*"
    state: absent
  ignore_errors: True
  when: repo_type == 75

- name: remove the old version rhevm
  yum:
    name: "rhevm*"
    state: absent
  ignore_errors: True
  when: repo_type == 74

- name: remove the old rhv release package
  yum:
    name: "rhv-release*"
    state: absent
  ignore_errors: True

- name: install the rhevm installer rpm
  yum:
    name: "{{ rhevm41_latest_installer }}"
    state: latest
  when: repo_type == 74

- name: install the rhevm installer rpm
  yum:
    name: "{{ rhevm42_latest_installer }}"
    state: latest
  when: repo_type == 75

- name: install latest rhvm
  yum:
    name: "rhvm*"
    state: latest
    skip_broken: yes
  when: repo_type == 75

- name: install latest rhevm
  yum:
    name: "rhevm"
    state: latest
    skip_broken: yes
  when: repo_type == 74

- name: update ovirt-engine-dwh-setup package
  yum:
    name: ovirt-engine-dwh-setup
    state: latest

- name: run answerbot in engine-setup mode
  command: /tmp/answerbot -i
